x=input('Enter an integer between 0 and 10:')
print(type(x))
print(x)
x=int(input('Enter an integer between 0 and 10:'))
print(type(x))
print(x)
x=float(input('Enter an float between 0 and 10:'))
print(type(x))
print(x)
x=eval(input('Enter an integer between 0 and 10:'))
print(type(x))
print(x*3)
x=eval(input('Enter an integer between 0 and 10:'))
print(type(x))
print(x*3)